language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov

# command to run tests
script:
  - py.test -s --cov=shop-poc tests/
#test

after_success:
  - codecov
